config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :searches
  devise_for :users, controllers: { 
    sessions: "users/sessions" }
  get 'emailsignup'  => 'emailapi#index'
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  resources "contacts", only: [:new, :create]

  root to: 'pages#index'
  resources :conversations, only: [:index, :show, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]
  
  get "/messages/new/:id" => "messages#new", :as => :new_message_with_parameter
  get '/newticket' => 'tickets#new'
  delete 'empty_trash', to: 'conversations#empty_trash'
  get "/faq" => 'pages#faq'
  get "/thankyou" => 'emailapi#thankyou'
  get "/signup" => 'pages#signup'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]
  include Mobylette::RespondToMobileRequests
  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end
  
  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  # def empty_trash
  #   @mailbox.trash.each do |conversation|
  #     conversation.receipts_for(current_user).update_all(deleted: true)
  #   end
  #   # current_user.mailbox.trash.conversations.each do |i| i.delete end
  #   flash[:success] = 'Your trash was cleaned!'
  #   redirect_to conversations_path
  # end

  def empty_trash
    current_user.mark_as_deleted(current_user.mailbox.trash.to_a)
    redirect_to conversations_path
  end

  def show
    @unread_count=get_mailbox.inbox(:read => false).count(:id, :distinct => true).to_s
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end
  
  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
  
  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
  end
  
  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<% if conversation.is_unread?(current_user) %>
  <li class="list-group-item clearfix" style="font-size: 20px;">
  <%= link_to conversation.subject, conversation_path(conversation) %>
<% else %>
  <li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
<% end %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>

      <% if conversation.is_unread?(current_user) %>
      <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                  class: 'btn btn-xs btn-info', method: :post %>

      <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <% gravatar_for participant %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<% content_for :title, "Inbox" %>

<% header "Your Inbox (#{current_user.mailbox.inbox(:unread => true).count(:id, :distinct => true)})" %>

<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
  	<% if @box == 'trash' %>
	    <p><%= link_to 'Empty trash', empty_trash_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></p>
  	<% end %>
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<% content_for :title, "Conversation" %>
<% header "Conversation" %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <% gravatar_for message.sender, 45, message.sender.name %>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.name %>
              says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
            <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>