config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :searches
  devise_for :users, controllers: { 
    sessions: "users/sessions" }
  get 'emailsignup'  => 'emailapi#index'
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  resources "contacts", only: [:new, :create]

  root to: 'pages#index'
  resources :conversations, only: [:index, :show, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]
  
  get "/messages/new/:id" => "messages#new", :as => :new_message_with_parameter
  get '/newticket' => 'tickets#new'
  delete 'empty_trash', to: 'conversations#empty_trash'
  get "/faq" => 'pages#faq'
  get "/thankyou" => 'emailapi#thankyou'
  get "/signup" => 'pages#signup'

end

app/views/pages/faq.html.erb
<% content_for :title, "FAQ" %>

<% header "Frequently Asked Questions" %>

<h4 style="margin-top: 25px; margin-bottom: 5px"><li>What is SeatSwappr?</li></h4>
SeatSwappr is currently an online marketplace for passengers to sell, search, buy and swap seats. Passengers may want to swap seats for many reasons, such as sitting next to family or friends, obnoxious passenger, more space, etc. SeatSwappr facilitates that swap by putting passengers in touch with each other.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Can SeatSwappr issue new boarding passes?</li></h4>
Currently, SeatSwappr cannot issue new boarding passes. That is why we ask passengers to board with their original boarding passes and swap once on the plane. We hope to work with airlines to issue new boarding passes once both parties have agreed.

<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Will there be a SeatSwappr app?
When?</li></h4>
Yes, SeatSwappr is working towards building an app for Android and iOS. Currently, SeatSwappr does not have a date for the release of the app.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Where is SeatSwappr available?</li></h4>
SeatSwappr is available globally.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Why would I want to sell or swap my seat?</li></h4>
Good Karma! If you are comfortable sitting in any seat and want to be accommodating to families, friends, and couples.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Can I charge to swap my seat?</li></h4>
SeatSwappr is actively looking to make this a feature of the site. Stay tuned.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>What are some examples of people looking to swap seats?</li></h4>
A couple who booked last minute and do not have seats together, a family whose parents and children cannot don’t have seats together, a passenger looking for a window or aisle seat but has a middle seat right now, a passenger who may want a seat with more legroom, a passenger who wants to sit in the front of the plane to exit faster to catch their connection.
 
<h4 style="margin-top: 25px; margin-bottom: 5px"><li>Do airlines let passengers swap seats?</li></h4>
Yes, as long as both passengers have a issued ticket on the same flight. Seat swaps occur on most flights anyways. Swapping between cabins, such as First Class and Economy, is not allowed, but you can swap within your cabin. If swapping to an exit row, you must meet the needs of the Airlines exit row seating requirements.

app/views/pages/index.html.erb
<% content_for :title, "SeatSwappr" %>

<% content_for :top_content do %>
  <div class="jumbotron" style="text-align: center;">
    <div class="container">
  	     <img class="img-responsive" src="img/logo/logo2.png" alt="Logo">
  	     <p>Tired of assigned seats?</p>
         <p>Swap your seat with SeatSwappr!</p>
  	     <% if user_signed_in? %>
          <div class="fb-like" data-href="http://www.facebook.com/seatswappr" data-layout="button" data-action="like" data-show-faces="false" data-share="true"></div>
          <div style="margin-top: 5px;"><a href="https://twitter.com/seatswappr" class="twitter-follow-button" data-show-count="false" >Follow @SeatSwappr</a></div>
         <% else %>
          <p><%= link_to 'Register Now', new_user_registration_path, class: 'btn btn-primary btn-lg' %></p>
     	<% end %>
    </div>
    <div class="social" style="padding-top: 20px;">
      <a href="https://www.facebook.com/SeatSwappr" class="btn btn-theme"><span class="faspan"><i class="fa fa-facebook"></span></i></a>
      <a href="https://twitter.com/seatswappr" class="btn btn-theme"><span class="faspan"><i class="fa fa-twitter"></i></span></a>
      <a href="https://plus.google.com/110380317606391783958/" class="btn btn-theme"><span class="faspan"><i class="fa fa-google-plus"></i></span></a>      
    </div>
    <div class="social">
        <p>Follow our blog:<a href="http://seatswappr.tumblr.com/" class="btn btn-theme"><span class="faspan"><i class="fa fa-tumblr"></i></span></a></p>
      </div>
  </div>
<% end %>


<!-- About Us -->
<div class="AboutUs" style="text-align: center; margin-bottom: 50px;">
  <div class="about">
    <h3 class="sectionheading">About</h3>
    <hr>
    <p class="lead"><strong>Oh No!  </strong>You don’t have seats together for your domestic or long direct international flight? You don't like the seat assigned to you by the airline? You want to be closer to the front of the plane to deplane faster? You just want to swap your seat because you can? 
    </p>
    <p class="lead"><strong>Don't Worry!  </strong>SeatSwappr is a peer to peer seat exchange where you can negotiate a seat swap with other passengers prior to boarding. We hope to eliminate the pre-boarding anxiety of asking fellow passengers to swap seats.
    </p>
    <br>
  </div>
  <!-- How it Works -->
  <h3 class="sectionheading">How it Works</h3>
  <hr>
  <div class="row">
    <div class="col-sm-3 feature-box-container">
      <div class="feature-box wow fadeInDown">
        <div class="icon">
          <i class="fa fa-usd"></i>
        </div>
        <div class="description">
          <h4>Sell</h4>
          <p>Passengers who don’t mind swapping will first post their seats for sale on SeatSwappr</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3 feature-box-container">
      <div class="feature-box wow fadeInDown">
        <div class="icon">
          <i class="fa fa-search"></i>
        </div>
        <div class="description">
          <h4>Search</h4>
          <p>Passengers looking for a better seat search for the desired seat(s) for swap on their flight</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3 feature-box-container">
      <div class="feature-box wow fadeInDown" data-wow-delay="0.2s">
        <div class="icon">
          <i class="fa fa-commenting"></i> 
        </div>
        <div class="description">
          <h4>Communicate</h4>
          <p>If you find a seat you want, start the conversation. Send the passenger a request to swap seats</p>
        </div>
      </div>
    </div>
    <div class="col-sm-3 feature-box-container">
      <div class="feature-box wow fadeInDown" data-wow-delay="0.4s">
        <div class="icon">
          <i class="fa fa-retweet"></i>
        </div>
        <div class="description">
          <h4>Swap</h4>
          <p>After the swap details are determined, simply swap seats after boarding with your original boarding pass.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Team -->
<!-- Team -->
  <h3 class="sectionheading">Our Team</h3>
  <hr>
  <div class="carousel-wrapper" style="height: 400px;">
    <span id="target-item-1"></span>
    <span id="target-item-2"></span>
    <span id="target-item-3"></span>
    <span id="target-item-4"></span>
    <div class="carousel-item item-1">
      <div class="col-sm-4 col-md-3">
        <div class="thumbnail">
          <img src="img/portraits/1.jpg" alt="shreyas.jpg">
          <div class="caption">
            <h3>Shreyas Parikh</h3>
            <p>He made the swapping seats site idea come to life.</p>
            <p><a href="https://www.facebook.com/Shrey.Parikh8484" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
            <a href="https://www.linkedin.com/pub/shreyas-parikh/30/390/132" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
          </div>
        </div>
      </div>
        <a class="arrow arrow-prev" href="#target-item-4"></a>
        <a class="arrow arrow-next" href="#target-item-2"></a>
    </div>

    <div class="carousel-item item-2">
      <div class="col-sm-4 col-md-3">
        <div class="thumbnail">
          <img src="img/portraits/4.jpg" alt="neha.jpg">
          <div class="caption">
            <h3>Neha Parikh</h3>
            <p>She knows analytics and how to use social media.</p>
            <p><a href="https://www.facebook.com/neha.sachdev.315" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
            <a href="https://www.linkedin.com/in/neha-parikh-4a49912b" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
          </div>
        </div>
      </div>
        <a class="arrow arrow-prev" href="#target-item-1"></a>
        <a class="arrow arrow-next" href="#target-item-3"></a>
    </div>

    <div class="carousel-item item-3">
      <div class="col-sm-4 col-md-3">
        <div class="thumbnail">
          <img src="img/portraits/2.jpg" alt="dan.jpg">
          <div class="caption">
            <h3>Daniel Rosino</h3>
            <p>He can do wonders with HTML/CSS.</p>
            <p><a href="https://www.facebook.com/daniel.rosino" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
            <a href="https://www.linkedin.com/pub/dan-rosino/1/b76/829" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
          </div>
        </div>
      </div>
      <a class="arrow arrow-prev" href="#target-item-2"></a>
      <a class="arrow arrow-next" href="#target-item-4"></a>
    </div>
    <div class="carousel-item item-4">
      <div class="col-sm-4 col-md-3">
        <div class="thumbnail">
          <img src="img/portraits/3.jpg" alt="gunjan.jpg">
          <div class="caption">
            <h3>Gunjan Patel</h3>
            <p>He has the marketing ideas and strategies.</p>
            <p><a href="https://www.facebook.com/patelgunjan" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
            <a href="https://www.linkedin.com/in/patelgunjan" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
          </div>
        </div>
      </div>
      <a class="arrow arrow-prev" href="#target-item-3"></a>
      <a class="arrow arrow-next" href="#target-item-1"></a>
    </div>
  </div>

<!-- Contact Us -->
<div class="contact" style="margin-bottom: 30px; margin-top: 10px;">
  <h3 class="sectionheading">Contact</h3>
  <hr>
    <div class="row">
      <div class="col-sm-6">
        <p><strong>What do you think?</strong> Please let us know if you have question or any suggestions to make SeatSwappr even better. We would love to hear from you. SeatSwappr base:</p>
        <ul class="list-contacts">
          <!--<li><i class="fa fa-phone"></i></li>
          <li><i class="fa fa-mobile-phone"></i></li>-->
          <li><i class="fa fa-map-marker"></i> New York, New York</li>
        </ul>
      </div>
      <div class="col-sm-6">
        <%= render :partial => "contacts/form", :locals => {:contact => Contact.new} %>
      </div>  
    </div>
</div>

app/views/pages/index.mobile.erb
<% content_for :title, "SeatSwappr" %>

<div data-role="header" data-position="fixed"> 
	<h1>SeatSwappr </h1>
        
      <% unless user_signed_in? %>
      <%= link_to 'Sign Up', new_user_registration_path, "class" => "ui-btn-right" %>

      <% else %>
        <%= link_to "New Seat", new_ticket_path, method: "get", "class" => "ui-btn-right" %>
      <% end %>
</div>

<div data-role="content" data-ajax="false"> 

<% if user_signed_in? %>
<h2>My Seats</h2>


<% current_userid = current_user.id %>
    <% current_userid %>
    <% if @ticket.count==0 %>
      <h3>You have not posted any seats</h3>
    <% else %>

    <ul data-role="listview">
        <% @ticket.each do |ticket| %>
            <li><%= link_to "#{ticket.departure_date}: #{ticket.airline}, Seat: #{ticket.seat_num}", ticket_path(ticket.id), method: :get %></li>
        <% end %>
      </ul>
    <% end %>

<% else %>
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <p><%= f.label :email %><br />
    <%= f.text_field :email %></p>

    <p><%= f.label :password %><br />
    <%= f.password_field :password %></p>

    <% if devise_mapping.rememberable? -%>
      <p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>
    <% end -%>

    <p><%= f.submit "Log In" %></p>
  <% end %>

  <%= render :partial => "devise/shared/links" %>

  <% end %>
</div>

app/views/pages/signup.html.erb
<% content_for :title, "SeatSwappr-Coming Soon" %>

<body class="landing">

	<% content_for :top_content do %>
	  <div class="jumbotron" style="text-align: center;">
	    <div class="container">
  	     <img class="img-responsive" src="img/logo/logo2.png" alt="Logo">
  	     <h1 style="font-weight: bold;">COMING SOON</h1>
  	     <p>Tired of assigned seats? Swap your seat with SeatSwappr!</p>
         <p>Would you like to help with beta testing? Join our mailing list to keep up with the latest on SeatSwappr!</p>

<!-- Begin MailChimp Signup Form -->
	<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">

	<form action="//seatswappr.us1.list-manage.com/subscribe/post?u=e256d8d94b71d2e7b9185643c&amp;id=c8c018d127" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>


	<div class="mc-field-group">
			<input type="email" value="" name="EMAIL" id="fieldname1" placeholder="Email Address" style="color: black;">

			<input type="text" value="" name="MMERGE3" id="fieldname2" placeholder="Zip Code" style="color: black;" >

		 	<input type="submit" value="Subscribe" name="subscribe" class="btn btn-primary">
	</div>

	  <div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	</form>

	<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[3]='MMERGE3';ftypes[3]='zip';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->


	   </div>
	    <div class="social" style="padding-top: 20px;">
	      <a href="https://www.facebook.com/SeatSwappr" class="btn btn-theme"><span class="faspan"><i class="fa fa-facebook"></span></i></a>
	      <a href="https://twitter.com/seatswappr" class="btn btn-theme"><span class="faspan"><i class="fa fa-twitter"></i></span></a>
	      <a href="https://plus.google.com/110380317606391783958/" class="btn btn-theme"><span class="faspan"><i class="fa fa-google-plus"></i></span></a>      
	    </div>
	    <div class="social">
	    	<p>Follow our blog:<a href="http://seatswappr.tumblr.com/" class="btn btn-theme"><span class="faspan"><i class="fa fa-tumblr"></i></span></a></p>
	    </div>

	  </div>
	<% end %>

	<!-- About Us -->
	<div class="AboutUs" style="text-align: center; margin-bottom: 50px;">
	  <div class="about">
	    <h3 class="sectionheading">About</h3>
	    <hr>
	    <p class="lead"><strong>Oh No!  </strong>You don’t have seats together for your domestic or long direct international flight? You don't like the seat assigned to you by the airline? You want to be closer to the front of the plane to deplane faster? You just want to swap your seat because you can? 
	    </p>
	    <p class="lead"><strong>Don't Worry!  </strong>SeatSwappr is a peer to peer seat exchange where you can negotiate a seat swap with other passengers prior to boarding. We hope to eliminate the pre-boarding anxiety of asking fellow passengers to swap seats.
	    </p>
	    <br>
	  </div>
	  <!-- How it Works -->
	  <h3 class="sectionheading">How it Works</h3>
	  <hr>
	  <div class="row">
	    <div class="col-sm-3 feature-box-container">
	      <div class="feature-box wow fadeInDown">
	        <div class="icon">
	          <i class="fa fa-usd"></i>
	        </div>
	        <div class="description">
	          <h4>Sell</h4>
	          <p>Passengers who don’t mind swapping will first post their seats for sale on SeatSwappr</p>
	        </div>
	      </div>
	    </div>
	    <div class="col-sm-3 feature-box-container">
	      <div class="feature-box wow fadeInDown">
	        <div class="icon">
	          <i class="fa fa-search"></i>
	        </div>
	        <div class="description">
	          <h4>Search</h4>
	          <p>Passengers looking for a better seat search for the desired seat(s) for swap on their flight</p>
	        </div>
	      </div>
	    </div>
	    <div class="col-sm-3 feature-box-container">
	      <div class="feature-box wow fadeInDown" data-wow-delay="0.2s">
	        <div class="icon">
	          <i class="fa fa-commenting"></i> 
	        </div>
	        <div class="description">
	          <h4>Communicate</h4>
	          <p>If you find a seat you want, start the conversation. Send the passenger a request to swap seats</p>
	        </div>
	      </div>
	    </div>
	    <div class="col-sm-3 feature-box-container">
	      <div class="feature-box wow fadeInDown" data-wow-delay="0.4s">
	        <div class="icon">
	          <i class="fa fa-retweet"></i>
	        </div>
	        <div class="description">
	          <h4>Swap</h4>
	          <p>After the swap details are determined, simply swap seats after boarding with your original boarding pass.</p>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>

	<!-- Team -->
	<h3 class="sectionheading">Our Team</h3>
	<hr>
	<div class="carousel-wrapper" style="height: 400px;">
	  <span id="target-item-1"></span>
	  <span id="target-item-2"></span>
	  <span id="target-item-3"></span>
	  <span id="target-item-4"></span>
	  <div class="carousel-item item-1">
	    <div class="col-sm-4 col-md-3">
	      <div class="thumbnail">
	        <img src="img/portraits/1.jpg" alt="shreyas.jpg">
	        <div class="caption">
	          <h3>Shreyas Parikh</h3>
	          <p>He made the swapping seats site idea come to life.</p>
	          <p><a href="https://www.facebook.com/Shrey.Parikh8484" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
	          <a href="https://www.linkedin.com/pub/shreyas-parikh/30/390/132" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
	        </div>
	      </div>
	    </div>
	      <a class="arrow arrow-prev" href="#target-item-4"></a>
	      <a class="arrow arrow-next" href="#target-item-2"></a>
	  </div>

	  <div class="carousel-item item-2">
	    <div class="col-sm-4 col-md-3">
	      <div class="thumbnail">
	        <img src="img/portraits/4.jpg" alt="neha.jpg">
	        <div class="caption">
	          <h3>Neha Parikh</h3>
	          <p>She knows analytics and how to use social media.</p>
	          <p><a href="https://www.facebook.com/neha.sachdev.315" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
	          <a href="https://www.linkedin.com/in/neha-parikh-4a49912b" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
	        </div>
	      </div>
	    </div>
	      <a class="arrow arrow-prev" href="#target-item-1"></a>
	      <a class="arrow arrow-next" href="#target-item-3"></a>
	  </div>

	  <div class="carousel-item item-3">
	    <div class="col-sm-4 col-md-3">
	      <div class="thumbnail">
	        <img src="img/portraits/2.jpg" alt="dan.jpg">
	        <div class="caption">
	          <h3>Daniel Rosino</h3>
	          <p>He can do wonders with HTML/CSS.</p>
	          <p><a href="https://www.facebook.com/daniel.rosino" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
	          <a href="https://www.linkedin.com/pub/dan-rosino/1/b76/829" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
	        </div>
	      </div>
	    </div>
	    <a class="arrow arrow-prev" href="#target-item-2"></a>
	    <a class="arrow arrow-next" href="#target-item-4"></a>
	  </div>
	  <div class="carousel-item item-4">
	    <div class="col-sm-4 col-md-3">
	      <div class="thumbnail">
	        <img src="img/portraits/3.jpg" alt="gunjan.jpg">
	        <div class="caption">
	          <h3>Gunjan Patel</h3>
	          <p>He has the marketing ideas and strategies.</p>
	          <p><a href="https://www.facebook.com/patelgunjan" class="btn btn-theme"><i class="fa fa-facebook"></i></a>
	          <a href="https://www.linkedin.com/in/patelgunjan" class="btn btn-theme"><i class="fa fa-linkedin"></i></a></p>
	        </div>
	      </div>
	    </div>
	    <a class="arrow arrow-prev" href="#target-item-3"></a>
	    <a class="arrow arrow-next" href="#target-item-1"></a>
	  </div>
	</div>

	<!-- Contact Us -->
	<div class="contact" style="margin-bottom: 30px; margin-top: 10px;">
	  <h3 class="sectionheading">Contact</h3>
	  <hr>
	    <div class="row">
	      <div class="col-sm-6">
	        <p><strong>What do you think?</strong> Please let us know if you have question or any suggestions to make SeatSwappr even better. We would love to hear from you. SeatSwappr base:</p>
	        <ul class="list-contacts">
	          <!--<li><i class="fa fa-phone"></i></li>
	          <li><i class="fa fa-mobile-phone"></i></li>-->
	          <li><i class="fa fa-map-marker"></i> New York, New York</li>
	        </ul>
	      </div>
	      <div class="col-sm-6">
	        <%= render :partial => "contacts/form", :locals => {:contact => Contact.new} %>
	      </div>  
	    </div>
	</div>
</body>