config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :searches
  devise_for :users, controllers: { 
    sessions: "users/sessions" }
  get 'emailsignup'  => 'emailapi#index'
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  resources "contacts", only: [:new, :create]

  root to: 'pages#index'
  resources :conversations, only: [:index, :show, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]
  
  get "/messages/new/:id" => "messages#new", :as => :new_message_with_parameter
  get '/newticket' => 'tickets#new'
  delete 'empty_trash', to: 'conversations#empty_trash'
  get "/faq" => 'pages#faq'
  get "/thankyou" => 'emailapi#thankyou'
  get "/signup" => 'pages#signup'

end

app/models/search.rb
class Search < ActiveRecord::Base
	belongs_to :user

	def search_tickets
		if departure_airport.blank? && airline.blank? && flight_num.blank? && departure_date.blank?
			tickets = []
		else			
			tickets = Ticket.all
			tickets = tickets.where("departure_airport LIKE ?","%#{departure_airport}%") if departure_airport.present?
			tickets = tickets.where("airline LIKE ?","%#{airline}%") if airline.present?
			tickets = tickets.where("flight_num LIKE ?","%#{flight_num}%") if flight_num.present?
			tickets = tickets.where(departure_date: departure_date) if departure_date.present?


			# tickets = tickets.where(["departure_date.to_date = #{departure_date}"])
			# tickets = tickets.where(["departure_date LIKE ?", "%#{departure_date}%"]) if departure_date.present?
			return tickets
		end
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	include Mobylette::RespondToMobileRequests
	def new
		@search = Search.new
		@airlines= Ticket.uniq.pluck(:airline)
		@departure_airports= Ticket.uniq.pluck(:departure_airport)
	end

	def create
		@search=Search.create(search_params)

		if @search.savedsearch == true
			@search.userid = current_user.id
			@search.save
		end		

		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
		session[:search_results] = request.url
	end

	private
	def search_params
		params.require(:search).permit(:departure_airport, :airline, :flight_num, :departure_date, :seat_num, :price, :savedsearch)
	end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<% content_for :title, "Search Seats" %>

<h3>Search Seats</h3>
	<%= link_to "Back", tickets_path %>

	<%= simple_form_for @search do |s| %>
	<div class="form-group">
		<%= s.label "Departure Date: ", :class => "searchlabels" %>
		<%= s.date_field :departure_date, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= s.label "Departure Airport: ", :class => "searchlabels" %>
		<%= s.select(:departure_airport, options_for_select(@departure_airports), {:include_blank => true}, id: 'simple-example3', class: 'form-control' ) %>
	</div>

	<div class="form-group">
		<%= s.label "Airline: ", :class => "searchlabels" %>
		<%= s.select(:airline, options_for_select(@airlines), {:include_blank => true}, id: 'simple-example4', class: 'form-control' ) %>
	</div>
	
	<div class="form-group">
		<%= s.label "Flight Number: ", :class => "searchlabels" %>
		<%= s.text_field :flight_num, class: 'form-control'  %>
	</div>

<!-- 	 <div class="form-group">
		<%= s.label "Save Search Criteria: " %><br/>
	  <%= s.check_box :savedsearch %>
	 </div>
 -->

	<div class="actions">
		<%= s.submit "Search", class: 'btn btn-primary' %>
	</div>
	<% end %>
	<br>

app/views/searches/show.html.erb
<% content_for :title, "Search Results" %>
<h3> Search Results </h3>

    <%= link_to "Back to search", new_search_path %>
    <% if @search.search_tickets.empty? %>
    	<h4>No seats available for this flight. Please check back later.</h4>

    <% else %>
    <div>
    	<table class="table">      
        <thead>
          <tr>
            <th>Departure Date</th>
            <th>Departure Airport</th>
            <th>Airline</th>
            <th>Flight Number</th>
            <th>Seat Number</th>
            <th>Seat Description</th>
            <th>Price</th>
            <th>User</th>
          </tr>
        </thead>
        <tbody>
          <% @search.search_tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.departure_date %></td>
              <td><%= ticket.departure_airport %></td>
              <td><%= ticket.airline %></td>
              <td><%= ticket.flight_num %></td>
              <td><%= ticket.seat_num %></td>
              <td><%= ticket.seat_desc %></td>
              <td><%= number_to_currency(ticket.price) %></td>
              <% if current_user %>
                <% user = User.find_by_id(ticket.user_id) %>
                <% email = User.find_by_id(ticket.user_id).email %>
                <% username = User.find_by_id(ticket.user_id).username %>

                <td><%= link_to "Contact ticket holder", new_message_path(to: user.id, ticket:ticket) %></td>
    	  			<% else %>
    	  				<td><%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %></td>
    	 				 <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
      </div>