config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :searches
  devise_for :users, controllers: { 
    sessions: "users/sessions" }
  get 'emailsignup'  => 'emailapi#index'
  post 'emailapi/subscribe' => 'emailapi#subscribe'
  resources "contacts", only: [:new, :create]

  root to: 'pages#index'
  resources :conversations, only: [:index, :show, :destroy]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :restore
    end
  end
  
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :mark_as_read
    end
  end
  resources :messages, only: [:new, :create]
  
  get "/messages/new/:id" => "messages#new", :as => :new_message_with_parameter
  get '/newticket' => 'tickets#new'
  delete 'empty_trash', to: 'conversations#empty_trash'
  get "/faq" => 'pages#faq'
  get "/thankyou" => 'emailapi#thankyou'
  get "/signup" => 'pages#signup'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Seatswappr - Swap or switch my airline seat. Peer to Peer exchange to swap seats on flights. Swap airline seats. Air Travel.">
    <meta name="author" content="SeatSwappr">
    
    <title><%= yield(:title) %></title>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'autocomplete-rails.js' %>
    <%= csrf_meta_tags %>


    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="img/favicon/favicon.ico" type="image/x-icon">
  </head>

  <body>
    
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <%= link_to root_path do %>
           <%= image_tag "/img/logo/logoSeatSwappr.png", class: 'navbar-brand' %>
        <% end %>

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
        <% new_messages = current_user.mailbox.inbox(:unread => true).count(:id, :distinct => true) %>
          <ul class="nav navbar-nav">
              <li><%= link_to "My Account (#{current_user.username})", edit_user_registration_path %></li>
              <li><%= link_to "My Inbox (#{new_messages})", conversations_path %></li>
              <li><%= link_to "View My Seats", tickets_path, method: "get" %></li>
              <li><%= link_to "Sell New Seat", new_ticket_path, method: "get" %></li>
              <li><%= link_to "Search Seats", new_search_path %></li>
              <li><%= link_to "FAQ", faq_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
          <% else %>
          <ul class="nav navbar-nav">
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to "FAQ", faq_path %></li>
          </ul>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>



    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <%= yield :top_content %>

    <div class="container">
        <h3><%= yield :header %></h3>
      <%= yield %>

    <hr>
      <footer class="footer">
      <h5> © Copyright 2015 Seatswappr All Rights Reserved </h5>
     </footer>

    </div>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-72777568-1', 'auto');
      ga('require', 'linkid');
      ga('require', 'displayfeatures');
      ga('send', 'pageview');
    </script>
   

  </body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    
      <!-- Include jQuery Mobile stylesheets -->
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'autocomplete-rails.js' %>
      <%= javascript_include_tag :application %>


      <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

      <!-- Include the jQuery library -->
      <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>

      <!-- Include the jQuery Mobile library -->
      <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
      <%= csrf_meta_tag %>


  </head>
    <base href="/">
    
  <body>
    
    <div data-role="page" id="home" data-url="<%= request.path %>">
    
      <div data-role="header">
        
      </div>
       
      <%= yield %>
      <% if user_signed_in? %>

        <div data-role="footer" data-position="fixed", style="text-align: center;">
        <%= link_to "My Seats", tickets_path, method: "get"  %>
         <%= link_to "Search", new_search_path %>
         <%= link_to "Inbox", conversations_path %>
         <%= link_to "Me", edit_user_registration_path %>
         <a href="#popupMenu" data-rel="popup" data-role="button" data-inline="true" data-icon="arrow-u">More</a>
          <div data-role="popup" id="popupMenu">
            <ul data-role="listview" data-inset="true" >
              <li><%= link_to "FAQ", faq_path %></li>
              <li><%= link_to "About Us", faq_path %></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        </div>
        <% else %>
        <% end %>
  </div>

  

</body>
</html>